# Generated by Django 4.2.3 on 2023-07-16 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0003_customer_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='isActive',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='isActive',
            new_name='is_active',
        ),
    ]
